### ISSUE TITLE
Ability to specify the redirect_uri in PkceLoginConfig()

### ISSUE THREAD

**Issue by willthetanman** [CamiloTerevinto/TerevintoSoftware.PythonPkceClient#1]
For example I had to modify the library to include "/callback" as a suffix in my redirect_uri, but it would be nice to be able to do this in the actual config when creating object. 

eg. For my use case I had to change:

`redirect_uri = **f"http://localhost:{self.__login_config.internal_port}" `
to
`redirect_uri** = f"http://localhost:{self.__login_config.internal_port}/callback"`

**Comment by CamiloTerevinto** [comment]
Hey @willthetanman, thanks for your comment. I've now added support for this through `PkceLoginConfig` in release 0.0.2.

Let me know if this works for you 😊

**Comment by willthetanman** [comment]
Much appreciated! this works perfectly.
